- name: variables in playbook
  hosts: localhost
  vars:
   course: "devops"
   trainer: "ravi"
   duration: "120hr"
  tasks:
  - name: variables in playbook
    ansible.builtin.debug:
     msg: "Hi I am learning {{course}}, My trainer is {{trainer}}, and duration is {{duration}}"